
INSERT INTO tb_menu_list (name) VALUES ('Pizzas');
INSERT INTO tb_menu_list (name) VALUES ('Porções');

INSERT INTO tb_menu (title, img_url, short_description, long_description, price) VALUES ('Pizza', '/main/resources/pizza-4queijos.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.' , 35.00);
INSERT INTO tb_menu (title, img_url, short_description, long_description, price) VALUES ('Pizza', '/main/resources/pizza_calabresa_e_mussarela.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.' , 30.00);
INSERT INTO tb_menu (title, img_url, short_description, long_description, price) VALUES ('Pizza', '/main/resources/pizza-vegetariana.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.' , 20.00);

INSERT INTO tb_menu (title, img_url, short_description, long_description, price) VALUES ('Porção de Picanha', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/porcao-de-picanha-com.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.' , 35.00);
INSERT INTO tb_menu (title, img_url, short_description, long_description, price) VALUES ('Porção de Coração', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/porcao-de-coracao.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.' , 30.00);
INSERT INTO tb_menu (title, img_url, short_description, long_description, price) VALUES ('Porção de Filé com Fritas', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/porcao-de-file-com-fritas.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.' , 20.00);

INSERT INTO tb_belonging (list_id, menu_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, menu_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, menu_id, position) VALUES (1, 3, 2);


INSERT INTO tb_belonging (list_id, menu_id, position) VALUES (2, 4, 0);
INSERT INTO tb_belonging (list_id, menu_id, position) VALUES (2, 5, 1);
INSERT INTO tb_belonging (list_id, menu_id, position) VALUES (2, 6, 2);
